[package]
name = "aqueue"
version = "0.3.0"
authors = ["luyi <luyikk@126.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/luyikk/aqueue"
documentation = "https://docs.rs/aqueue"
description = "fast speed thread safe async execute queue."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
aqueue_trait = {path="async-trait",version="0.1.0"}
concurrent-queue = "1.2.2"
async-oneshot = "0.4.2"