name: Publish Crates

on:
  push:
    tags:
      - v[0-9]+.*
      
defaults:
  run:
    shell: bash

jobs:
  create-release:
     name: Create GitHub release
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3
        with:
           persist-credentials: false
      - name: Install Rust
        run: rustup update stable --no-self-update
      - run: cargo package
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: "CHANGELOG.md"
          title: "queue $version"
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Login to Cargo
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo login --registry=https://github.com/login
      - name: Publish Package
        run: |
          cargo publish

